name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check out font project source repository
        uses: actions/checkout@v4
      - name: Install the latest stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install fontc and compile fonts
        uses: googlefonts/fontc-action@main
        with:
          source-path: fonts/David CLM/DavidCLM-Medium.otf

      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            25-03-2025.typ
            27-03-2025.typ

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: "*.pdf"

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          body: >
            Auto release API ${{env.RELEASE_TAG}} by @ci

            Typst github action by @lvignoli
          files: "*.pdf"
