name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: sudo apt update
      - run: sudo apt install snapd
      - run: sudo snap install typst

      - run: typst compile 25-03-2025.typ --font-path fonts
      - run: typst compile 27-03-2025.typ --font-path fonts
      - run: typst compile 01-04-2025-tergul.typ --font-path fonts
      - run: typst compile 01-04-2025.typ --font-path fonts
      - run: typst compile 03-04-2025.typ --font-path fonts
      # - run: typst compile 03-04-2025-tergul.typ --font-path fonts
      - run: typst compile 22-04-2025-tergul.typ --font-path fonts

      - run: typst compile ex2.typ --font-path fonts
      - run: typst compile ex3.typ --font-path fonts

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: "*.pdf"

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          body: >
            Auto release API ${{env.RELEASE_TAG}} by @ci
          files: "*.pdf"
