name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: sudo apt update
      - run: sudo apt install snapd
      - run: sudo snap install typst

      - run: typst compile 2025-03-25.typ --font-path fonts
      - run: typst compile 2025-03-27.typ --font-path fonts
      - run: typst compile 2025-04-01-tergul.typ --font-path fonts
      - run: typst compile 2025-04-01.typ --font-path fonts
      - run: typst compile 2025-04-03.typ --font-path fonts
      # - run: typst compile 2025-04-03-tergul.typ --font-path fonts
      - run: typst compile 2025-04-22-tergul.typ --font-path fonts
      - run: typst compile 2025-04-24.typ --font-path fonts
      # - run: typst compile 2025-04-24-tergul.typ --font-path fonts
      - run: typst compile 2025-04-29.typ --font-path fonts
      - run: typst compile 2025-05-06-tergul.typ --font-path fonts
      - run: typst compile 2025-05-06.typ --font-path fonts
      - run: typst compile 2025-05-08.typ --font-path fonts
      # - run: typst compile 2025-05-08-tergul.typ --font-path fonts
      # - run: typst compile 2025-05-13-tergul.typ --font-path fonts
      - run: typst compile 2025-05-13.typ --font-path fonts
      - run: typst compile 2025-05-15.typ --font-path fonts
      # - run: typst compile 2025-05-20-tergul.typ --font-path fonts
      - run: typst compile 2025-05-22.typ --font-path fonts
      - run: typst compile 2025-05-27.typ --font-path fonts

      - run: typst compile ex1.typ --font-path fonts
      - run: typst compile ex2.typ --font-path fonts
      - run: typst compile ex3.typ --font-path fonts
      - run: typst compile ex4.typ --font-path fonts
      - run: typst compile ex5.typ --font-path fonts
      - run: typst compile ex6.typ --font-path fonts
      - run: typst compile ex7.typ --font-path fonts
      - run: typst compile ex8.typ --font-path fonts

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: "*.pdf"

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          body: >
            Auto release API ${{env.RELEASE_TAG}} by @ci
          files: "*.pdf"
